### ISSUE TITLE
Request: Quicky for Nuxt 3

### ISSUE THREAD

**Issue by luminous8** [alohe/quicky#4]
Hi,

I love what you've done with Quicky, but I'm a Nuxt user and I'd love to use it for my Nuxt apps

Do you think it could be adapted for Nuxt SSR and static apps?

Thanks 🙏

**Comment by alohe** [comment]
I'll check it out. =)

**Comment by alohe** [comment]
@luminous8, I'm curious as to why there isn't a standard start script in Nuxt. how do you typically build and run your projects?

**Comment by luminous8** [comment]
I don't know Nextjs but i assume Nuxt & Next are similar (i know they have the same similar rendering mode - static / ssr etc)

Basically with Nuxt
- If your app is static you have to run `npm run generate` and the html files to serve are in `.output/public`
- if your app requires a server, you hate to run `npm run build` and the server file is `node .output/server/index.mjs`

**Comment by alohe** [comment]
I see, so those are the two standard options?

**Comment by luminous8** [comment]
yes exactly!

**Comment by alohe** [comment]
Damn, Nuxt is a mess. The fact that they don't have a standard start script and you need to jump through a bunch of hoops to get it working properly is tedious. I'm pushing this feature back for now. =)
