### ISSUE TITLE
Can not be used with NVM-Manager  // pm2 missing

### ISSUE THREAD

**Issue by goldjunge91** [alohe/quicky#6]
hi,
first i run in the Problem that your Tool dont work with NVM Manager. 
After this i got the following error:
SSL certificate obtained and configured for URL
"/bin/sh: 1: pm2: not found
Failed to start the webhook server: Command failed: pm2 start /home/user/.quicky/webhook/index.js --name "quicky-"
"
then when i try "quicky webhooks"
Enter the URL where the webhook will be received (e.g., quicky.example.com):domainname
Directory /home/jetwash/.quicky/webhook already exists and is not empty. Deleting...
[PM2] Applying action stopProcessId on app [quicky-webhook-server](ids: [ 0 ])
[PM2] [quicky-webhook-server](0) ✓
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ quicky-webhook-se… │ fork     │ 0    │ stopped   │ 0%       │ 0b       │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
[PM2] Applying action deleteProcessId on app [quicky-webhook-server](ids: [ 0 ])
[PM2] [quicky-webhook-server](0) ✓
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘

last error is this: Unhandled Rejection at: [object Promise], reason: Error: Domain webhook1.domain.de is already configured in Nginx
i have to make a new subdomain

**Comment by alohe** [comment]
Just pushed an update to improve domain management functionality.

Please ensure you're using the LTS version (0.0.92) for optimal performance and compatibility.

To check or update to the LTS version, run:
- `quicky -v` to check the version number  
- `quicky upgrade` to update  

Let me know if the issues you experienced are resolved or if you encounter anything else!
